puppetlabs/puppetlabs-lvm

lib/puppet/provider/logical_volume/lvm.rb

We use dashes in our LV names and they are automatically escaped by LVM (The dashes are doubled). When we create VG myvg and LV my-lv, the lvcreate device is /dev/mapper/myvg-my--lv.
This only affects dmsetup remove. The other LVM commands and outputs use the unescaped names.
I'm not sure if a new set of tests should be created or if the current create and destroy test should be modified to use myvg/my-lv so I didn't make any spec changes.

escape dashes in lv name for dmsetup remove

---

lib/puppet/provider/filesystem/lvm.rb

Sometimes `blkid` shows a `SEC_TYPE="ext2"` in addition to `TYPE="ext3"`.
It has something to do with a filesystem being backwards compatible with
ext2. This commit fixes the regex that matches TYPE=.. to prevent it
from matching SEC_TYPE.
Unfortunately I couldn't figure out how to add a test case for this. Any advice welcome if you think a test is necessary, thanks!

Fix filesystem type detection

---

manifests/logical_volume.pp

Allow root filesystems to have pass specified as 1 instead of 2; allow the default dump value to be overridden if desired.

Allow different values for pass and dump

---

lib/puppet/provider/logical_volume/lvm.rb
lib/puppet/type/logical_volume.rb
spec/unit/puppet/provider/logical_volume/lvm_spec.rb

Resubmitting from a newly rebased branch with a single commit. I retracted the previous pull request which was submitted 4 months ago.
Example for mirrors:
package { "lvm2":
ensure => "installed"
}
#-----------------------------------------------------------------
#-----------------------------------------------------------------
$lvm_file_system="ext4"              # ext4 or xfs, xfs can not be resized by this version of this puppet module
$vgname="mmvg"                       # name of Volume Group
$lvname="mmlv"                       # name of Logical Volume
$devices=["/dev/sdb1","/dev/sdb2"]   # Physical Devices
$lv_fs_size="2G"                     # Size of Logical Volume
physical_volume { [$devices]:
ensure => present
}
volume_group { "${vgname}":
ensure => present,
physical_volumes …

mirrors - rc 3

---

manifests/logical_volume.pp
manifests/volume_group.pp

Hi, thank you all for this fine module! I have a couple of issues though (and a proposal for solution).
1) When using the lvm class I discovered that the resources are created in random order, so what happens is, the code fails because the vg can't be created on non-existent pv, mkfs can't create file systems on none-existent logvols and so on. This happens and is reproducable when provision several devices. Another example, vgcreate will fail if the drive has an msdos label (in lack of --yes parameter), which happens often, I guess (given eg clearpart --all in anaconda). However, if those drives are pvcreated first, it works. These problems are addressed in manifests/volume_group.pp line 13 and manifests/logical_volume.pp line 58.
2) The other issue is with the creation of logical …

Ordering of resources and removal of some defaults in class lvm

---

manifests/logical_volume.pp
manifests/volume.pp
manifests/volume_group.pp

When an `undef` value is passed as `lvm::logical_volume` name, `mkfs` is called with unwanted command line like
```
Error: Execution of 'mkfs.ext4 /dev/rootvg/' returned 1: mke2fs 1.42.9 (28-Dec-2013)
/dev/rootvg/ is not a block special device.
Proceed anyway? (y,n)
Error: /Stage[main]/Main/Lvm::Logical_volume[undef]/Filesystem[/dev/rootvg/]/ensure: change from absent to present failed: Execution of 'mkfs.ext4 /dev/rootvg/' returned 1: mke2fs 1.42.9 (28-Dec-2013)
/dev/rootvg/ is not a block special device.
Proceed anyway? (y,n)
```
This does not break anything, but we're here protected by `mkfs` that asks for confirmation (this fails in batch mode).
This patch only introduces a stupid test to check that `$name` isn't  `undef`.
My software versions:
* `CentOS 7`
* `puppet v3.7.2`
* `ruby …

Handle undef value in lvm::logical_volume

---

lib/puppet/type/logical_volume.rb
spec/unit/puppet/type/logical_volume_spec.rb

regular expression was incorrectly using character classes and matching strings like: 100( or 100v etc.

Fix bad regexp

---

spec/unit/facter/lvm_support_spec.rb

@DavidS - "puppet 2.7 calls all facts twice. recommended approach is to add '.at_least(1)' to expectations."

(maint) Fixes specs for Puppet ~> 2.7.0

---

lib/puppet/provider/physical_volume/lvm.rb
spec/unit/puppet/provider/physical_volume/lvm_spec.rb

You can now use the RAL to fetch current physical volumes:
```
$ puppet resource physical_volume
physical_volume { '/dev/sda2':
ensure => 'present',
}
```

(MODULES-2103) Adds RAL for physical_volume

---

lib/puppet/provider/filesystem/lvm.rb
manifests/logical_volume.pp
spec/unit/classes/lvm_spec.rb
spec/unit/puppet/provider/filesystem/lvm_spec.rb

This pull request is based on https://github.com/puppetlabs/puppetlabs-lvm/pull/57 / https://github.com/puppetlabs/puppetlabs-lvm/pull/89, which wasn't merged.
It would be great, if you could have another look at this pull request.

Add swap support.

---

manifests/logical_volume.pp

Not setting it should use the entire physical drive.

Made logical_volume $size an optional parameter

---

lib/puppet/provider/logical_volume/lvm.rb

1) The size property allows floating point values, but in the provider we
coerce the size string reported by lvm to an int, effectively
ignoring the decimal part at resize.
2) The regex used to extract size and unit from the desired size
doesn't match floating point values. It ends up matching the decimal
part of a floating point value in the first backreference.
This leads to the following issue breaking resizes when a floating point
value for size is set:
"""
Error: Decreasing the size requires manual intervention (103.06G <
71.06G)
Error:
/Stage[main]/S_puppetdb::Lvconfig/Profile_lvm::Fs_on_lv[root]/Logical_volume[root]/size:
change from 71.06G to 103.06G failed: Decreasing the size requires
manual intervention (103.06G < 71.06G)
"""
Because new_size_bytes is actually set to only the …

(logical_volume) Fix regex on new_size and coerce to float instead of int

---

manifests/logical_volume.pp

Currently lvm::logical_volume can not be invoked with the parameter size_is_minsize. This pr makes it configureable:
~~~puppet
node 'default' {
lvm::logical_volume {'test2':
volume_group   => "vgd_${hostname}",
size           =>'1M',
mountpath => '/mnt/test2',
pass => 2,
dump => 1,
size_is_minsize => 'true',
}
}
~~~

Make size_is_minsize usable from lvm::logical_volume

---

manifests/volume.pp

A simple Puppet lint pass. If you would like me to do rubocop that will be far more intensive. There are over 300 rubocop violations in the tests alone, and most of them should be fixed by hand.

(MODULES-3789) Lint the LVM Module's Puppet Code

---

README.md

~~Also splits out AIX specific attribute documentation into its own file.~~
Makes the README style more consistent.

(MODULES-2790) Improve README documentation

---

lib/puppet/type/logical_volume.rb
spec/unit/type/filesystem_spec.rb
spec/unit/type/logical_volume_spec.rb
spec/unit/type/physical_volume.rb

Is there anything  else we need to add tests for, for types and providers?
I also wasn't sure whether to squash the commits or not -- let me know if I should!

(MODULES-2706) types and providers

---

.travis.yml
CHANGELOG.md
Gemfile
metadata.json

Update changelog and bump version

Cut 0.6.0 release

---

lib/puppet/provider/physical_volume/lvm.rb
spec/unit/puppet/provider/physical_volume/lvm_spec.rb

passing a blank argument (when force => false) to the pvcreate method causes errors:
~]# puppet resource --debug --trace physical_volume /dev/sdc ensure=present
Debug: Executing: '/sbin/pvs /dev/sdc'
Debug: Executing: '/sbin/pvcreate  /dev/sdc'
Error: Execution of '/sbin/pvcreate  /dev/sdc' returned 5: Device  not found (or ignored by filtering).
Physical volume "/dev/sdc" successfully created
Which appear to be related to the insertion of the extra "nil" argument. Note the extra space in `/sbin/pvcreate  /dev/sdc`. This shouldn't matter if the command is executed 'as-is' on the commandline but there appears to possibly be some sort of quoting or grouping going on such that the command is literally `/sbin/pvcreate ' /dev/sdc'`, which causes an error. I'm not sure why the PV is still …

Fix issue with using force method as pvcreate argument

---

lib/puppet/provider/logical_volume/lvm.rb

Hello,
I noticed that the provider did not extended automatically the logical volume for a swap partition, so I've done this small change that follow the best practive for doing it.
swapoff (turn off swap)
mkswap (format the logical volume again, so it uses the whole size)
swapon (put swap back online).
Best Regards

Added support to the resize of a logical volume with swap

---

README.md
manifests/logical_volume.pp
spec/unit/classes/lvm_spec.rb

This patch allows a logical_volume to be made ready, but not mounted. 
This allows for the actual mount to be done after data is migrated to the new volume.

Added support for volumes not mounted by lvm.

---

lib/puppet/provider/logical_volume/lvm.rb
lib/puppet/type/logical_volume.rb
spec/unit/puppet/provider/logical_volume/lvm_spec.rb

Currently changing the size of a logical volume using the lvm provider on our Xen dom0 causes issues for us because the volume is exposed to a vm and is mounted there but the volume does not appear mounted to the host. Therefore, resize2fs tries to do an offline resize on the volume which causes issues. This adds a "resize_fs" flag to the logical_volume type that, when set to false, will not attempt that resize.

(MODULES-3230) Add flag to Logical_volume to not resize filesystem

---

lib/puppet/provider/logical_volume/lvm.rb

Looks like there is a non-ascii-space in the file.
Please merge to avoid errors like
--
Error: invalid byte sequence in US-ASCII
Error: /File[/var/lib/puppet/lib/puppet/provider/logical_volume/lvm.rb]/content: change from {md5}a53348a0ebcbad43c7ad2b0ffd0d2f75 to {md5}95476cfb372e7c165a14c9a126ea9383 failed: invalid byte sequence in US-ASCII
Info: Loading facts
--
Thanks,
Fabian

fixed charset in provider/logical_volume/lvm.rb

---

manifests/logical_volume.pp

Bugfix: exec "swapoff for '${mount_title}'" must be applied before unmount swap partition.
Part of puppet report without bugfix:
```
Notice: /Stage[main]/Lvm/Lvm::Volume_group[default]/Lvm::Logical_volume[swap]/Mount[/dev/default/swap]/ensure: undefined 'ensure' from 'unmounted'
Info: Computing checksum on file /etc/fstab
Info: /Stage[main]/Lvm/Lvm::Volume_group[default]/Lvm::Logical_volume[swap]/Mount[/dev/default/swap]: Scheduling refresh of Exec[swapoff for '/dev/default/swap']
Notice: /Stage[main]/Lvm/Lvm::Volume_group[default]/Lvm::Logical_volume[swap]/Filesystem[/dev/default/swap]/ensure: removed
Error: Execution of '/sbin/dmsetup remove default-swap' returned 1: device-mapper: remove ioctl on default-swap failed: Device or resource busy
Command failed
Error: …
```

fixed: executed command 'swapoff' before unmount swap partion.

---

manifests/logical_volume.pp

Hi,
I think that PR#96 missed to add its new parameters to the define lvm::logical_volumes.
Here is my little PR to fix this.
Thanks.

Add missing parameters to manage mirrors for lvm::logical_volume.

---

lib/puppet/provider/logical_volume/lvm.rb
spec/unit/puppet/provider/logical_volume/lvm_spec.rb

lvs prints `2.5G` as `2.50g`. This makes puppet try to extend the lv if you ensure a volume with size of `2.5g`.
`lvextend` complains because of the same size and fails, breaking the puppet apply.
This commit strips zeros from floating point values from lvs ouptut.

Fix parsing size from lvs output

---

manifests/volume.pp

This commit fixes issue MODULES-4172.
Syntax error (using "+" with string) in fail message of volume.pp.
+ replaced with sprintf for concatanation error string.

[#puppethack] fix syntax error in volume.pp

---

README.md

(MODULES-3991) Docs Update

---

lib/puppet/provider/logical_volume/lvm.rb
spec/unit/puppet/provider/logical_volume/lvm_spec.rb

There is a bug which prevents user from adding a new logical volume if the volume name is the same as the volume group's name.
The regexp which parses the output of lvs command searches only for the name of the new logical volume. If the output contains previously added logical volumes, the regexp will match with the volume group's name of those volumes. Because the logical volume does not actually exist yet, the proceeding function which tries to extract the size of the new volume will fail.
This fix extends the regexp to match not only with the logical volume name put with the combination of logical volume name and the volume group name.
Example output of lvs command:
```
LV   VG   Attr       LSize Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
comp data -wi-ao---- 5.00g
root data …
```

Cannot add a new volume if the volume group has the same name. Fix: Better regexp for parsing the output of lvs

---

manifests/logical_volume.pp

According to docs https://github.com/puppetlabs/puppetlabs-lvm/blob/master/README.md, thinpool is default to false, but as we see in https://github.com/puppetlabs/puppetlabs-lvm/blob/master/manifests/logical_volume.pp#L24 it is default to undef and then it is always called in https://github.com/puppetlabs/puppetlabs-lvm/blob/master/manifests/logical_volume.pp#L92

Setting thinpool default to false

---

manifests/volume_group.pp

Like addressed in https://tickets.puppetlabs.com/browse/MODULES-4284, I am missing this parameter when using the new "by-path" functionality.

added (missing) followsymlinks parameter

---

manifests/logical_volume.pp

I would set the default for the dump mount option to 0. I'm not sure about the default with Redhat-based distributions but with Debian/Ubuntu the standard value seems to be 0. Is there a reason for the default value to be 1?

Set default mount option for dump to 0

---

lib/facter/lvm_support.rb
spec/unit/facter/lvm_support_spec.rb

This is a followup to here:
#98
I figured it was worth putting in a new request versus reopening the old one. I'd still like to get a timeout on a couple of the facts so that facter will return / doesn't hang on nodes with an underlying disk issue.
There appear to be two versions of valid syntax for the timeout - I used the first but I'm happy to rewrite with the second if preferred.
( [...] ,options = {:timeout => 30})
( [...] ,timeout: 30)
I set the timeout to 30 as a generic value, but I'm happy to adjust. I still wasn't sure how to pass a value from the Puppet code into the custom fact, but if I can get a pointer on that, I'd be happy to make that change as well.
I also added if statements around the lvm commands - because they are not in setcode blocks, the confines listed don't …

Update fact to add 30 second timeout; add ifs to restrict lvm commands

---

.gitignore
lib/puppet/provider/filesystem/lvm.rb
lib/puppet/provider/logical_volume/lvm.rb
manifests/logical_volume.pp
spec/unit/classes/lvm_spec.rb
spec/unit/puppet/provider/filesystem/lvm_spec.rb
spec/unit/puppet/provider/logical_volume/lvm_spec.rb

The exec resources running swapon and swapoff in the lvm::logical_volume
define type were running whenever a swap logical volume was created
or updated.
The logical_volume provider was also running these same commands on a swap
resize. This caused a conflict where the puppet run would error out
when the logical_volume provider attempted to run swapoff on a swap
lvm that had already been unloaded from swap and the lvm would never
be reloaded into swap.
When the exec resources were removed from the lvm::logical_volume
defined type, it created a gap wherein a NEW swap lvm would not be
loaded into swap after being created.
To solve this issue, I added the swapon command and logic that will
run that command against the filesystem resource if the fs_type parameter
is set to 'swap'

puppethack - MODULES-4753 and MODULES-4964

---

lib/puppet/provider/logical_volume/lvm.rb
manifests/logical_volume.pp
spec/unit/puppet/provider/logical_volume/lvm_spec.rb

There are several situations where Puppet will not increase the size of an LV but if you run the equivalent LVM command it will actually work. See [MODULES-4180](https://tickets.puppetlabs.com/browse/MODULES-4180).
Also changes the test to not expect such a specific Puppet error. Finally some minor whitespace and lint fixes.

Removing the 'extent size' check in logical_volume provider

---

lib/puppet/provider/logical_volume/lvm.rb
spec/unit/puppet/provider/logical_volume/lvm_spec.rb

Prior to this patch, if a logical_volume resource needed
to resize an lv that did not have a filesystem present,
blkid would fail and print an error even though the
operation was successful.  This patch rescues that exception
and pushes the message to the debug level.

(MODULES-4067) Gracefully handle blkid return code 2

---

lib/facter/lvm_support.rb

When lvm_support was not present, facter would still attempt to execute the vgs and pvs commands.

Don't execute the lvm commands when not supported.

---

lib/puppet/provider/filesystem/lvm.rb

#puppethack: Related to Ticket https://tickets.puppetlabs.com/browse/MODULES-5504
This is to fix the Lvm generated error when creating xfs on top of existing filesystem (returned 1: mkfs.xfs: /dev/mapper/myvg-mylv appears to contain an existing filesystem (ext4)).

#puppethack Fix error when creating XFS on top of another Filesystem

---

manifests/volume_group.pp

The line 11 checks if is_hash and that condition can't apply if the only acceptable type are Array and String
The error I got and that is fixed is:
parameter 'physical_volumes' expects a value of type Array or String, got Struct at ...

Added Hash as acceptable type for physical_volumes

---

.travis.yml

Update to travis file to account for issues that have arisen with the highest rubygem version below 2.3.0

(maint) - Fix rubygems-update for ruby < 2.3

---

metadata.json

This commit bumps the upper boundary of the stdlib dependency.
It should help avoid conflicts (librarian-puppet) such as:
```
[Librarian]   Module puppetlabs-lvm found versions: 1.1.0, 1.0.1, 1.0.0, 0.9.0, 0.8.0, 0.7.0, 0.6.0, 0.5.0, 0.4.0, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.0, 0.1.2, 0.1.1, 0.1.0, 0.0.1
[Librarian]     Checking puppetlabs-lvm/1.1.0 <https://forgeapi.puppetlabs.com>
[Librarian]       Resolved puppetlabs-lvm (< 2.0.0, >= 1.0.0) <https://forgeapi.puppetlabs.com> at puppetlabs-lvm/1.1.0 <https://forgeapi.puppetlabs.com>
[Librarian]   Resolved puppetlabs-lvm (< 2.0.0, >= 1.0.0) <https://forgeapi.puppetlabs.com>
[Librarian] Conflict between puppetlabs-stdlib (< 5.0.0, >= 4.13.1) <(no source specified)> and puppetlabs-stdlib/5.1.0 <https://forgeapi.puppetlabs.com>
```
We need to …

Allow puppetlabs-stdlib versions >= 5.0

---

lib/puppet/provider/logical_volume/lvm.rb

Hi everyone,
This PR should solve https://tickets.puppetlabs.com/browse/MODULES-9004 by using the mount point to resize an XFS file system instead of the volume. Without this change, file system resizing does not work with newer xfs versions (e.g. 4.19.0 under RHEL8).
As it is my first contribution, feel free to tell me if I missed something.
Thanks in advance!

(MODULES-9004) Resize XFS file system by mount point, not by volume

---

lib/puppet/type/volume_group.rb

The documentation (README) indicates that we can do this:
```
class { 'lvm':
volume_groups => {
'vg' => {
createonly => true,
physical_volumes => {
'/dev/sdb' => {
unless_vg => 'vg',
},
},
},
},
}
```
However, this results in a message like so:
```
2018-11-08 12:23:02 +0000 Puppet (err): Execution of '/sbin/vgcreate vg {"/dev/sdb"=>{"unless_vg"=>"vg"}}' returned 5: Device {"/dev/sdb"=>{"unless_vg"=>"vg"}} not found.
2018-11-08 12:23:02 +0000 /Stage[main]/Lvm/Lvm::Volume_group[vg]/Volume_group[vg]/ensure (err): change from 'absent' to 'present' failed: Execution of '/sbin/vgcreate vg {"/dev/sdb"=>{"unless_vg"=>"vg"}}' returned 5: Device {"/dev/sdb"=>{"unless_vg"=>"vg"}} not found.
```
The issue is that although the defines permit the passing of physical_volumes as a hash, the type/provider …

volume_group type does not handle passing of physical_volumes as a hash

---

lib/puppet/type/volume_group.rb

Reverts puppetlabs/puppetlabs-lvm#219

Revert "volume_group type does not handle passing of physical_volumes as a hash"

---

lib/puppet/provider/logical_volume/lvm.rb
spec/unit/puppet/provider/logical_volume/lvm_spec.rb

This PR builds on #230. In local testing all tests related to this PR pass while some facter-related tests failed on this branch and on master.
Prior to this commit a logical volume that was a substring of the name of a volume group could not be created due to a false positive by the `exists?` method of the provider.
The sample output of `lvs` in the spec tests was updated to this:
```
LV      VG         Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
lv_root VolGroup   -wi-ao----  18.54g
lv_swap VolGroup   -wi-ao---- 992.00m
data    data       -wi-ao---- 992.00m
j1      vg_jenkins -wi-a-----   1.00g
```
After adding a test to verify that a logical volume named `jenkins` does not exist the original `exists?` check failed like so:
``` …
```

Make lv that is a substring of a vg work

---

spec/unit/puppet/provider/logical_volume/lvm_spec.rb

Test that exists returns nil if the name of the logical volume is a
substring of the name of an existing logical volume.
(cherry picked from commit d64c11d098b940d3a2a0a96985adad75b8f46cb2)

Add a further test for #244

---

metadata.json

stdlib v9 is easily supported as there are no breaking changes relating to anything but Puppet/OS compatiblity.

Bump stdlib dependency to v9

---

REFERENCE.md
manifests/volume.pp

Fixes a typo with the extents parameter in volume.pp.
Fixes https://github.com/puppetlabs/puppetlabs-lvm/issues/290

(gh-290) - fix broken datatype for extents

---

REFERENCE.md
manifests/volume.pp

Fixes a typo found to be present for the ensure parameter
Fixes https://github.com/puppetlabs/puppetlabs-lvm/issues/293

(gh-293) - fix typo with ensure

---

lib/facter/lvm_support.rb
spec/unit/facter/lvm_support_spec.rb

This is reverting https://github.com/puppetlabs/puppetlabs-lvm/commit/8e1e8eb1718f31a75d9edf79b123c74d61364e55 and fixing the spec tests other way.
See issue #298 
Closes #298 .

[GH-298] fix lvm_vg_* facts

---

metadata.json

The *_core modules are internal modules and vendored within Puppet AIO. They should not be added to metadata.json.
Provide a detailed description of all the changes present in this pull request.

remove puppetlabs/mount_core from metadata.json

---

README.md
lib/facter/lvm_support.rb
spec/unit/facter/lvm_support_spec.rb

tested manually on nodes with and without lvm
Closes #307

fix issues on nodes without lvm

---

spec/acceptance/create_filesystem_spec.rb
spec/spec_helper_acceptance_local.rb

Fixing pipeline for ARM architecture due to the NVME device type for ARM OS.

(CAT-1696) - Fixing pipeline for ARM architecture

---

README.md
REFERENCE.md
lib/puppet/type/filesystem.rb
tasks/ensure_fs.json

- README: don't use deprecated top-scope syntax
- README: fix formatting
- README: fix spelling

Documentation fixes

---

lib/puppet/provider/volume_group/lvm.rb
lib/puppet/type/volume_group.rb
spec/unit/puppet/provider/volume_group/lvm_spec.rb
spec/unit/puppet/type/volume_group_spec.rb

Allow modifying the physical extent size when creating new volume groups.
Essentially replaces #332

Allow modifying the physical extent size for volume groups

---

lib/puppet/provider/logical_volume/lvm.rb
lib/puppet/type/logical_volume.rb
spec/acceptance/create_filesystem_spec.rb

Adding new getters and setters for stripes.

CAT-1912 : Adding new getters and setters for stripes & not allowing change of stripes for an existing lvm
