Gemfile
manifests/volume.pp

To make it Puppet 4 compliant.

Fix unquoted strings in cases

---

lib/puppet/provider/logical_volume/lvm.rb
spec/unit/puppet/provider/logical_volume/lvm_spec.rb

https://tickets.puppetlabs.com/browse/MODULES-1801

Fix MODULES-1801 - also escape volume group names

---

.gitignore
.rspec

RSpec 2 fixup and ignore the .bundle folder

make the rspec tests run

---

lib/puppet/provider/physical_volume/aix.rb
lib/puppet/provider/volume_group/aix.rb
lib/puppet/type/logical_volume.rb

Added support for defining logical volume sizes in the "logical partition" (LP) quantity. This is useful in AIX
Added support for managing volume groups in AIX

More AIX support

---

lib/puppet/provider/filesystem/lvm.rb
lib/puppet/type/filesystem.rb
spec/unit/puppet/provider/filesystem/lvm_spec.rb

Fix for https://tickets.puppetlabs.com/browse/MODULES-2215

Support mkfs_cmd - fixes MODULES-2215

---

lib/facter/lvm_support.rb
spec/unit/facter/lvm_support_spec.rb

sometimes it might be interesting to know which pvs are within the
existing vgs

add a fact that list all pvs in a vg

---

lib/puppet/provider/physical_volume/lvm.rb
lib/puppet/type/physical_volume.rb
spec/unit/puppet/provider/physical_volume/lvm_spec.rb

This PR adds the ability to pass the "force" option to pvcreate.

add force option for physical_volume

---

manifests/init.pp

Reopening https://github.com/puppetlabs/puppetlabs-lvm/pull/71

Manage lvm2 package

---

lib/puppet/provider/logical_volume/lvm.rb
lib/puppet/type/logical_volume.rb
manifests/logical_volume.pp
spec/unit/puppet/provider/logical_volume/lvm_spec.rb

Rebased  #106 and fixed up the tests.

Add the --type argument to lvcreate

---

lib/puppet/provider/filesystem/aix.rb
lib/puppet/type/filesystem.rb

(MODULES-3881) in which unit output is corrected and whitespace removed

---

Gemfile
lib/puppet/type/volume_group.rb

new parameter to tell volume_group Type to resolve PV symlinks to real devices, and override insync? method to do this

resolve /dev/disk/by-path/xxxx symlinks to block devices

---

CHANGELOG.md
metadata.json

updates changelog and metadata

(FM-5990) release prep for 0.9.0

---

CHANGELOG.md
metadata.json

This includes the following:
- metadata bump
- Change log entry for this release
- Formatting changes for the CHANGELOG

Release Prep 1.0.0

---

tasks/mount_lv.rb

Don't know how we missed this one, whoops.

(maint) Removed test code that missed review

---

.fixtures.yml
.travis.yml
metadata.json

Adds tests for Puppet 5 and 6 and adds the mount dependency that the module requires in Puppet >=6

Added test matrix for Puppet 6

---

.github/workflows/pr_test.yml
.github/workflows/spec.yml
.sync.yml

This should go along with #273, it adds the testing workflows.

Forgot to add the test workflows

---

.github/workflows/nightly.yml

Fixes broken echo in nightly.yml

(maint) - Update nightly.yml

---

.github/pull_request_template.md

CONT-990_Adding PR template

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
Gemfile

Provide a detailed description of all the changes present in this pull request.

Maint update litmus provision

---

.github/workflows/ci.yml
lib/facter/lvm_support.rb

Provide a detailed description of all the changes present in this pull request.

(maint) - fix rubocop

---

README.md
metadata.json

LVM is "Logical Volume Manager". References:
* https://gitlab.com/lvmteam/lvm2/-/blob/fe822f704305b6bda5ebdf915a4f40be89f5ec67/man/lvm.8_main#L14
* https://en.wikipedia.org/w/index.php?title=Logical_Volume_Manager_(Linux)&oldid=1197143413

README, metadata: correct name of LVM in summaries

---

.github/workflows/ci.yml

(maint) - Update CI Workflows

---

.gitignore
.pdkignore
.vscode/extensions.json
Gemfile
metadata.json
spec/spec_helper.rb

Updating pdk version with 3.2.0.

MAINT : Updating pdk version with 3.2.0

---

.gitignore
.pdkignore
Gemfile
metadata.json

(PF-3525) - pdk update for module
pdk version: `3.2.0`

pdksync - (PF-3525) - pdk update for module

---

lib/puppet/provider/filesystem/aix.rb
lib/puppet/provider/logical_volume/aix.rb

Update legacy facts with their respective counterparts.

(CAT-2230) Update legacy facts

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
manifests/init.pp

MODULES-11577 chore(ruby): upgrade Ruby from 2.7 to 3.1
